accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup , name = "signup"),
    path("profile/", views.profile , name = "profile"),
    path("profile/edit/", views.profile_edit , name = "profile_edit"),
    path("profile/password/", views.password_change , name = "password_change"),
]

blog/urls.py
from django.urls import path
from . import views
app_name = "blog"

urlpatterns = [
    path("",views.PostList.as_view(), name= "post_list" ),
    path("<slug:slug>", views.PostDetail.as_view(),name= "post_detail" ),
    path("category/<str:slug>", views.PostByCategory.as_view(),name= "post_by_category" ),
    path("tag/<slug:slug>", views.PostByTag.as_view(),name= "post_by_tag" ),
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from .settings import MEDIA_ROOT

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),    
    path('summernote/', include('django_summernote.urls')),
    path('', include('about.urls', namespace = "about")),
    path("blog/", include("blog.urls", namespace= "blog")),
    path("Property/", include("property.urls", namespace= "property")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings. MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

def user_dir_path(instance, filename):
    return 'user/{0}/profile_photo/{1}'.format(instance.user, filename)

GENDER = [ 
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]

class Profile(models.Model):
    user = models.ForeignKey(User, verbose_name=_("user"), related_name="user_profile", on_delete=models.CASCADE)
    profile_image = models.ImageField(_("profile_image"), upload_to=user_dir_path)
    gender = models.CharField(_("Gender"), max_length=10, choices=GENDER)
    country = CountryField(blank= True)

    def __str__(self):
        return str(self.user)
    
@receiver(post_save, sender=User)  
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.forms import ValidationError 
from .models import User, Profile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,PasswordChangeForm


class RegisterationForm(UserCreationForm):

    def clean(self):
       email = self.cleaned_data.get('email')
       if User.objects.filter(email=email).exists():
            raise ValidationError("This Email is already exists with deffirent user")

       
       return self.cleaned_data
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ( "email",)



class UserEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username', 'email']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Profile, User

from .forms import RegisterationForm , UserEditForm, ProfileEditForm, PasswordChangeForm
from django.contrib.auth import authenticate , login
# Create your views here.

def signup(request):
    signup_form = RegisterationForm
    if request.method == "POST":
        signup_form = RegisterationForm(data=request.POST)
        if signup_form.is_valid():
            signup_form.save()
            
            username = signup_form.cleaned_data['username']
            password = signup_form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect(reverse('accounts:profile'))

    return render(request, "registration/signup.html", {"form" : signup_form})

def profile(request):
    user = User.objects.get(id = request.user.id)
    profile = Profile.objects.get(user = user)
    context ={
        "user" : user,
        "profile" : profile      
              }
    return render(request, "profile/profile.html",context )

def profile_edit(request):
    user = request.user
    profile =Profile.objects.get(user = user)
    user_form = UserEditForm( instance= user)
    profile_form = ProfileEditForm(instance = profile)
    if request.method == "POST":
        user_form = UserEditForm(request.POST, instance = user)
        profile_form = ProfileEditForm(request.POST, request.FILES, instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            account = profile_form.save(commit = False)
            account.user = user
            account.save()
            return redirect(reverse('accounts:profile'))
    context= {
        "form" : user_form,
        "profile_form" : profile_form
    }
    return render(request, "profile/profile_edit.html", context)

def password_change(request):
    password_form = PasswordChangeForm(user = request.user)
    if request.method == "POST":
        password_form = PasswordChangeForm(user = request.user, data=request.POST)
        if password_form.is_valid():
            password_form.save()
            password = password_form.cleaned_data['new_password1']
            user = authenticate(username=request.user.username ,password=password)
            login(request,user)
            return redirect(reverse('accounts:profile'))

    return render(request, "registration/password_change.html", {"form" : password_form})

accounts/templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block style %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 600px;
        margin: auto;
        text-align: center;
        font-family: arial;
    }

    .title {
        color: grey;
        font-size: 18px;
    }
    button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

    a {
        text-decoration: none;
        font-size: 22px;
        color: black;
    }

    button:hover,
    a:hover {
        opacity: 0.7;
    }
</style>
{% endblock style %}
    
{% block body %}


<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/image_5.jpg'%});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">
                    <span class="mr-2"><a href="/">Home</a></span> <span>Profile</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Profile</h1>
            </div>
        </div>
    </div>
</div>


<div class="card mt-5">
    <div class="col-md-8 mx-auto">
        <img src="{{profile.profile_image.url}}" alt="User" style="width:100%">
        <h2 class = "mt-3" >{{user.first_name}} {{user.last_name}}</h2>
        <h6>@{{user.username}}</h6>
        <h6> {{user.email}}</h6>
        <div style="margin: 24px 0;">
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin ml-5"></i></a>
            <a href="#"><i class="fa fa-facebook ml-5"></i></a>
        </div>
        <button><a id="edit" href="{% url 'accounts:profile_edit' %}">Edit  Profile</a></button>

    </div>
</div>


{% endblock body %}

accounts/templates/profile/profile_edit.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}


<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/image_5.jpg'%});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">
                    <span class="mr-2"><a href="/">Home</a></span> <span>Profile</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Profile Edit</h1>
            </div>
        </div>
    </div>
</div>

<div class="container" style="margin-top: 80px;margin-bottom: 80px;">
    <div class="col-md-6  mx-auto">
        {% if form.errors %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <div id="form_errors">
                    {% for key, value in form.errors.items %}
                    <strong>{{ value }}</strong>
                    {% endfor %}
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_form profile_form %}
            {% bootstrap_button "Edit" button_type="submit" button_class="btn-primary" %}
        </form>
    </div>
</div>


{% endblock body %}