blog/urls.py
from django.urls import path
from . import views
app_name = "blog"

urlpatterns = [
    path("",views.PostList.as_view(), name= "post_list" ),
    path("<slug:slug>", views.PostDetail.as_view(),name= "post_detail" ),
    path("category/<str:slug>", views.PostByCategory.as_view(),name= "post_by_category" ),
    path("tag/<slug:slug>", views.PostByTag.as_view(),name= "post_by_tag" ),
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from .settings import MEDIA_ROOT

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),    
    path('summernote/', include('django_summernote.urls')),
    path('', include('about.urls', namespace = "about")),
    path("blog/", include("blog.urls", namespace= "blog")),
    path("Property/", include("property.urls", namespace= "property")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings. MEDIA_URL, document_root = settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from . import views

app_name = "property"

urlpatterns = [
    path('',views.PropertyList.as_view(), name = "property_list"),
    path('new',views.property_create, name = "add_property"),
    path('<slug:slug>',views.property_detail, name = "property_detail"),
]

property/models.py
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django.utils.text import slugify
from django.core.validators import MaxValueValidator as maxx_length, MinValueValidator as minn_length
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
# Based On The DirEngine Template the Models will be Created

COUNT= {
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
}

class Property(models.Model):
    owner = models.ForeignKey(User, verbose_name=_("property_owner"), on_delete=models.CASCADE)
    name = models.CharField(_("name"), max_length=50)
    title = models.CharField(_("title"), max_length=50, null=True, blank=True)
    image = models.ImageField(_("main_image"), upload_to="property/images")
    price = models.IntegerField(_("price"),default=0)
    descritpion = models.TextField(_("descritpion"))
    place = models.ForeignKey("Place", verbose_name=_("places"),related_name= 'property_places', on_delete=models.CASCADE)
    category = models.ForeignKey("Category", verbose_name=_("category"), related_name="property_category", on_delete=models.CASCADE)
    created_at = models.DateTimeField(_("created_at"), default= timezone.now )
    avilablity = models.BooleanField(_("avilabilty"), null=True, blank=True)
    slug = models.CharField(_("slug"), max_length=50, null=True, blank=True)

    def save(self, *args, **kwargs ):
        if not self.slug:
            self.slug = slugify(self.name)
        return super(Property,self).save(*args, **kwargs)
        
    def __str__(self):
        return self.name
    
    def get_related (self):
        related = Property.objects.filter(place = self.place)[:3]
        return(related)

    def get_absolute_url(self):
        return reverse("property:property_detail", kwargs={"slug": self.slug})

    def avg_rating(self):
        all_reviews = self.property_Reviews.all()
        rating = 0
        if all_reviews:
            for rate in all_reviews:
               rating += rate.rate
            return [round(rating/len(all_reviews),1), len(all_reviews)]
        else:
            return [rating, len(all_reviews)]
    
    def check_avilablity(self, date_from, date_to):
        now = timezone.now().date()
        books = self.property_booked.filter(date_to__gt = now)
        if books:
            for book in books:
                if book.date_to > date_from and book.date_from <= date_to :
                    return False
            return True
        else: 
            return True

    class Meta:
        ordering = ["price"]

class PropertyImages(models.Model):
    property = models.ForeignKey(Property, verbose_name=_("property"),related_name="property_images", on_delete=models.CASCADE)
    image = models.ImageField(_("image"), upload_to="property/images")

    def __str__(self):
        return str(self.property)

class Place(models.Model) :
    name = models.CharField(_("name"), max_length=50)
    image = models.ImageField(_("image"), upload_to="place/images")

    def __str__(self):
        return str(self.name)


class Category(models.Model):
    name = models.CharField(_("name"), max_length=50)
    icon = models.CharField(_("icon"), max_length=50)
    
    def __str__(self):
        return str(self.name)
    

class Review(models.Model):
    property = models.ForeignKey(Property, verbose_name=_("property"), related_name="property_Reviews", on_delete=models.CASCADE)
    rate = models.IntegerField(_("rate"), validators=[maxx_length(5), minn_length(0)], default=0)
    content = models.CharField(_("content"), max_length=150)
    created_at = models.DateTimeField(_("created_at"), default= timezone.now )
    author = models.ForeignKey(User, verbose_name=_("author"), related_name="review_author", on_delete=models.CASCADE)

    def __str__(self):
        return f'{str(self.property)} Review by {str(self.author)}'


class Book(models.Model):
    user = models.ForeignKey(User, verbose_name=_("user"), related_name="property_user", on_delete=models.CASCADE)
    created_at = models.DateTimeField(_("created_at"),  default= timezone.now)
    property = models.ForeignKey(Property, verbose_name=_("property"), related_name="property_booked", on_delete=models.CASCADE)
    date_from = models.DateField(_("booked from"), default= timezone.now)
    date_to = models.DateField(_("booked to"), default= timezone.now)
    guests = models.IntegerField(_("guests"), choices=COUNT)
    childerns = models.IntegerField(_("childerns"), choices=COUNT, null=True, blank=True)

    def __str__(self):
        return f'{str(self.property)} Booked by {str(self.user)}'

property/forms.py
from django import forms
from django.forms import formset_factory
from .models import Property, PropertyImages, Book, Review, timezone


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ["name", "title", "image", "price", "descritpion", "place", "category"]

class PropertyImagesForm(forms.ModelForm):
    class Meta:
        model = PropertyImages
        fields = ['image']

PropertyImagesFormsets = formset_factory(
    PropertyImagesForm,
    extra=4,

)

class DateInput(forms.DateInput):
    input_type = 'date'
    format=('%d/%m/%Y')

class BookForm(forms.ModelForm):
    def clean(self):
        now = timezone.now().date()
        start_date = self.cleaned_data.get('date_from')
        end_date = self.cleaned_data.get('date_to')
        if now > start_date:
            raise forms.ValidationError("start date must be later than or equal today" )
        elif end_date <= start_date:
            raise forms.ValidationError("End date must be later than start date")
        return self.cleaned_data
    
    class Meta:
        model = Book
        fields = ["date_from", "date_to", "guests", "childerns"]
        widgets = {
            'date_from': DateInput(),
            'date_to': DateInput(),
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["content", "rate"]

property/views.py
from django.shortcuts import redirect, render 
from .filter import PropertyFilter
from django.utils import timezone
from django.contrib import messages
from django.views.generic.edit import FormMixin
from django.views.generic import DetailView, ListView, FormView
from .forms import BookForm, ReviewForm, PropertyForm, PropertyImagesFormsets
from .models import Property, PropertyImages

# Create your views here.


class FilteredListView(ListView):
    filterset_class = None
    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context

class PropertyList(FilteredListView):
    model = Property
    paginate_by = 15
    filterset_class = PropertyFilter


def property_detail(request, slug):
    property = Property.objects.get(slug = slug)
    template = "property/property_detail.html"
    check_form = BookForm()
    review_form = ReviewForm()
    if request.method == 'POST':
        if "Availability" in request.POST:
            check_form = BookForm(request.POST)
            date_from = request.POST.get("date_from")
            if check_form.is_valid():
                date_from = check_form.cleaned_data["date_from"]
                date_to = check_form.cleaned_data["date_to"]
                myform = check_form.save(commit=False)
                is_avaliable = property.check_avilablity(date_from, date_to)
                if is_avaliable:
                    myform.property = property
                    myform.user = request.user
                    myform.save()
                    messages.success(request, "Avalible, Booked succesfully")
                else :
                    messages.warning(request, "Not Avaliable")

        elif "Review" in request.POST:
            review_form = ReviewForm(request.POST)
            if review_form.is_valid():
                myform = review_form.save(commit=False)
                myform.property = property
                myform.author = request.user
                myform.save()
                

    context = {
        "property": property,
        "review_form" : review_form,
        "avaliability_form" : check_form,
    }
    return render(request, template , context)

def property_create(request):
    form = PropertyForm()
    formset = PropertyImagesFormsets()
    if request.method == "POST":
        form = PropertyForm(request.POST, request.FILES)
        formset = PropertyImagesFormsets(request.POST, request.FILES)
        if form.is_valid() and formset.is_valid():
            property = form.save(commit= False)
            property.owner = request.user
            property.avilablity = False
            property.save()
            for image_form in formset:
                image = image_form.cleaned_data['image']
                PropertyImages.objects.create(property = property, image=image)
            return redirect("/Property")

    context = {
        "form" : form,
        "formset" : formset
    }
    return render(request, "property/new_property.html", context)

property/templates/property/new_property.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{% load bootstrap4 %}

<div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_5.jpg' %}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">
                    <span class="mr-2"><a href="/">Home</a></span> <span>Property</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">New Property</h1>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="col-lg-12">
                <form action="{% url 'property:add_property' %}" class="row" method="post" enctype="multipart/form-data">
                <div class="col-md-6 ftco-animate">
                    <div class="destination">
                        {% csrf_token %}
                        {% bootstrap_form form%}
                    </div>
                </div>
                <div class="col-md-6 ftco-animate">
                    <div class="destination">
                        {{ formset.management_form }}
                        {% for image_form in formset %}
                        {% bootstrap_form image_form %}
                        {% endfor %}
                    </div>
                </div>            
                {% bootstrap_button button_type="submit" content="Create Property" %}
            </form>
        </div>
    </div>
</section>

{% endblock body %}

property/templates/property/property_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{% load bootstrap4 %}
    
<div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_5.jpg' %}');">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
        <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
          <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">
            <span class="mr-2"><a href="index.html">Home</a></span> <span>Property</span></p>
          <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Properties</h1>
        </div>
      </div>
    </div>
  </div>



    <section class="ftco-section ftco-degree-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 sidebar">
                    <div class="sidebar-wrap bg-light ftco-animate">
                        <h3 class="heading mb-4">Find City</h3>
                        <form action="" method="get" class="form">
                            {% csrf_token %}
                            {% bootstrap_form filterset.form %}
                            
                            <div class="form-group">
                                {% bootstrap_button button_type="submit" content="Search" %}
                            </div>
                          </form>
                        <!-- 
                        <form action="#">
                            <div class="fields">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Destination, City">
                                </div>
                                <div class="form-group">
                                    <div class="select-wrap one-third">
                                        <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                        <select name="" id="" class="form-control" placeholder="Keyword search">
                                            <option value="">Select Location</option>
                                            <option value="">San Francisco USA</option>
                                            <option value="">Berlin Germany</option>
                                            <option value="">Lodon United Kingdom</option>
                                            <option value="">Paris Italy</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="text" id="checkin_date" class="form-control" placeholder="Date from">
                                </div>
                                <div class="form-group">
                                    <input type="text" id="checkin_date" class="form-control" placeholder="Date to">
                                </div>
                                <div class="form-group">
                                    <div class="range-slider">
                                        <span>
                                            <input type="number" value="25000" min="0" max="120000" /> -
                                            <input type="number" value="50000" min="0" max="120000" />
                                        </span>
                                        <input value="1000" min="0" max="120000" step="500" type="range" />
                                        <input value="50000" min="0" max="120000" step="500" type="range" />
                                        </svg>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Search" class="btn btn-primary py-3 px-5">
                                </div>
                            </div>
                        </form> 
                        -->
                    </div>
                    <!-- <div class="sidebar-wrap bg-light ftco-animate">
                        <h3 class="heading mb-4">Star Rating</h3>
                        <form method="post" class="star-rating">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">
                                    <p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i
                                                class="icon-star"></i><i class="icon-star"></i><i
                                                class="icon-star"></i></span></p>
                                </label>
                            </div>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">
                                    <p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i
                                                class="icon-star"></i><i class="icon-star"></i><i
                                                class="icon-star-o"></i></span></p>
                                </label>
                            </div>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">
                                    <p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i
                                                class="icon-star"></i><i class="icon-star-o"></i><i
                                                class="icon-star-o"></i></span></p>
                                </label>
                            </div>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">
                                    <p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i
                                                class="icon-star-o"></i><i class="icon-star-o"></i><i
                                                class="icon-star-o"></i></span></p>
                                </label>
                            </div>
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">
                                    <p class="rate"><span><i class="icon-star"></i><i class="icon-star-o"></i><i
                                                class="icon-star-o"></i><i class="icon-star-o"></i><i
                                                class="icon-star-o"></i></span></p>
                                </label>
                            </div>
                        </form>
                    </div> -->
                </div>
                <div class="col-lg-9">
                    <div class="row">
                    
                        {% for property in object_list  %}   
                        <div class="col-md-4 ftco-animate">
                            <div class="destination">
                                <a href="{{property.get_absolute_url}}"
                                    class="img img-2 d-flex justify-content-center align-items-center"
                                    style="background-image: url({{property.image.url}});">
                                    <div class="icon d-flex justify-content-center align-items-center">
                                        <span class="icon-search2"></span>
                                    </div>
                                </a>
                                <div class="text p-3">
                                    <div class="d-flex">
                                        <div class="one">
                                            <h3><a href="{{property.get_absolute_url}}">{{property.name}}</a></h3>
                                            <p class="rate">
                                                {% for i in '12345'|make_list %}
                                                {% if forloop.counter <= property.avg_rating.0 %}
                                                <i class="icon-star"></i>
                                                {% else %}
                                                <i class="icon-star-o"></i>
                                                {% endif %}
                                                {% endfor %}
                                                <span>{{property.avg_rating.0}}</span>
                                            </p>
                                        </div>
                                        <div class="two">
                                            <span class="price per-price">${{property.price}}<br><small>/night</small></span>
                                        </div>
                                    </div>
                                    <p>{{property.title|truncatewords:9}}</p>
                                    <hr>
                                    <p class="bottom-area d-flex">
                                        <span><i class="icon-map-o"></i> {{property.place}}</span>
                                        <span class="ml-auto"><a href="{{property.get_absolute_url}}">Book Now</a></span>
                                    </p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    {% if is_paginated %}
                    <div class="row mt-5">
                        <div class="col text-center">
                            <div class="block-27">
                                <ul>
                                    {% if page_obj.has_previous %}
                                        <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                                    {% else %}
                                        <li><a>&lt;</a></li>
                                    {% endif %}
                                    
                                    {% for i in paginator.page_range  %}
                                        {% if page_obj.number == i  %} 
                                            {% if page_obj.has_previous and page_obj.previous_page_number > 1  %}
                                                <li><a href="?page={{i|add:'-2'}}">{{i|add:"-2"}}</a></li>
                                                <li><a href="?page={{i|add:'-1'}}">{{i|add:"-1"}}</a></li>
                                            {% endif %}
                                            <li class="active"><span>{{i}}</span></li>
                                        {% endif %}
                                    {% endfor %}
                                    
                                    {% if page_obj.has_next %}
                                        <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                                    {% else%}
                                        <li><a>&gt;</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div> <!-- .col-md-8 -->
            </div>
        </div>
    </section> <!-- .section -->

{% endblock body %}