blog/urls.py
from django.urls import path
from . import views
app_name = "blog"

urlpatterns = [
    path("",views.PostList.as_view(), name= "post_list" ),
    path("<slug:slug>", views.PostDetail.as_view(),name= "post_detail" ),
    path("category/<str:slug>", views.PostByCategory.as_view(),name= "post_by_category" ),
    path("tag/<slug:slug>", views.PostByTag.as_view(),name= "post_by_tag" ),
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from .settings import MEDIA_ROOT

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),    
    path('summernote/', include('django_summernote.urls')),
    path('', include('about.urls', namespace = "about")),
    path("blog/", include("blog.urls", namespace= "blog")),
    path("Property/", include("property.urls", namespace= "property")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings. MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager
# Create your models here.

class Post(models.Model):
    title = models.CharField(_("title"), max_length=50)
    tags = TaggableManager()
    image = models.ImageField(_("image"), upload_to= "blog/posts/", height_field=None, width_field=None, max_length=None)
    author = models.ForeignKey(User, verbose_name=_("author"), related_name="post_author", on_delete=models.CASCADE)
    created_at = models.DateTimeField(_("created_at"), default= timezone.now )
    category = models.ForeignKey("Category", verbose_name=_("category"), related_name="post_category", on_delete=models.CASCADE)
    description = models.TextField(_("description"))
    #comment = models.ForeignKey("Comment", verbose_name=_("comment"), related_name="post_comments", on_delete=models.CASCADE)
    slug = models.CharField(_("slug"), max_length=50, null=True, blank=True)

    def save(self, *args, **kwargs ):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Post,self).save(*args, **kwargs)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ["created_at"]
    

class Comment(models.Model):
    pass


class Category(models.Model):
    name = models.CharField(_("name"), max_length=50)
    image = models.ImageField(_("image"), upload_to="blog/category/")

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from .models import Post, Category
from taggit.models import Tag
from django.db.models import Q, Count
from django.views.generic import ListView, DetailView

class PostList(ListView):
    model = Post
    paginate_by = 15

    def get_queryset(self):
        search = self.request.GET.get('query','')
        post_list = Post.objects.filter(
            Q(title__icontains = search)|
            Q(description__icontains = search)
        )
        return post_list

class PostDetail(DetailView):
    model = Post

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = Category.objects.all().annotate(category_count = Count('post_category'))
        context["tags"] = Tag.objects.all()
        context["recent_posts"] = Post.objects.all()[:4]
        return context
    
class PostByCategory(ListView):
    model = Post

    def get_queryset(self):
        slug = self.kwargs['slug']
        post_list = Post.objects.filter(
            Q(category__name__icontains = slug)
        )
        return post_list

class PostByTag(ListView):
    model = Post

    def get_queryset(self):
        slug = self.kwargs['slug']
        post_list = Post.objects.filter(
            Q(tags__name__icontains = slug)
        )
        return post_list

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{% load bootstrap4 %}

<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_4.jpg'%});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                        class="mr-2"><a href="/">Home</a></span> <span class="mr-2"><a
                            href="/blog">Blog</a></span> <span>Blog Single</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Tips &amp;
                    Articles</h1>
            </div>
        </div>
    </div>
</div>


<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-8 ftco-animate">
                <h2 class="mb-3">{{post.title}}</h2>
                {{post.description}}
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">                
                        {% for tag in post.tags.all %}                        
                        <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag}}</a>
                        {% endfor %}
                    </div>
                </div>

                <div class="about-author d-flex p-5 bg-light">
                    <div class="bio align-self-md-center mr-5">
                        <img src="images/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc align-self-md-center">
                        <h3>Lance Smith</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                            necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente
                            consectetur similique, inventore eos fugit cupiditate numquam!</p>
                    </div>
                </div>


                <div class="pt-5 mt-5">
                    <h3 class="mb-5">Comments</h3>
                    <div id="disqus_thread"></div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-md-4 sidebar ftco-animate">
                <div class="sidebar-box">
                    <form action="{% url 'blog:post_list' %}" method="GET" class="search-form">
                        <div class="form-group">
                            <span class="icon fa fa-search"></span>
                            <input type="text" name= "query" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <div class="categories">
                        <h3>Categories</h3>
                        
                        {% for cat in category %}
                        <li><a href="{% url 'blog:post_by_category' cat %}">{{cat}} <span>{{cat.category_count}}</span></a></li>
                        {% endfor %}
                    </div>
                </div>

                <div class="sidebar-box ftco-animate">
                    
                    <h3>Recent Blog</h3>
                    
                    {% for recent_post in recent_posts %}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{recent_post.image.url}});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="{{recent_post.get_absolute_url}}"> {{recent_post.title}}</a></h3>
                            <div class="meta">
                                <div><a href="{{recent_post.get_absolute_url}}"><span class="icon-calendar"></span> {{recent_post.created_at|date:'F j Y'}}</a></div>
                                <div><a href="{{recent_post.get_absolute_url}}"><span class="icon-person"></span> {{recent_post.author}}</a></div>
                                <div><a href="{{recent_post.get_absolute_url}}"><span class="icon-chat"></span>10</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">
                        
                        {% for tag in tags  %}
                        <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag}}</a>
                        {% endfor %}
                            
                        
                    </div>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3>Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus
                        voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur
                        similique, inventore eos fugit cupiditate numquam!</p>
                </div>
            </div>

        </div>
    </div>
</section> <!-- .section -->
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */

    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = {{post.id}}; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://direngine.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<script id="dsq-count-scr" src="//direngine.disqus.com/count.js" async></script>
{% endblock body %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{% load bootstrap4 %}

<div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_4.jpg'%}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                        class="mr-2"><a href="index.html">Home</a></span> <span>Blog</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Tips &amp;
                    Articles</h1>
            </div>
        </div>
    </div>
</div>


<section class="ftco-section bg-light">
    <div class="container">
        <div class="row d-flex">
            
            {% for post in post_list  %}
            <div class="col-md-3 d-flex ftco-animate">
                <div class="blog-entry align-self-stretch">
                    <a href="{{post.get_absolute_url}}" class="block-20" style="background-image: url('{{post.image.url}}');">
                    </a>
                    <div class="text p-4 d-block">
                        <span class="tag">Tips, Travel</span>
                        <h3 class="heading mt-3"><a href="{{post.get_absolute_url}}">
                            {{post.title|truncatewords:6}}</a>
                        </h3>
                        <div class="meta mb-3">
                            <div><a href="{{post.get_absolute_url}}">{{post.created_at|date:'F j Y'}}</a></div>
                            <div><a href="{{post.get_absolute_url}}">{{post.author}}</a></div>
                            <div><a href="{{post.get_absolute_url}}" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row mt-5">
            <div class="col text-center">
                {% if is_paginated %}
                <div class="row mt-5">
                    <div class="col text-center">
                        <div class="block-27">
                            <ul>
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                                {% else %}
                                    <li><a>&lt;</a></li>
                                {% endif %}
                                
                                {% for i in paginator.page_range  %}
                                    {% if page_obj.number == i  %} 
                                        {% if page_obj.has_previous and page_obj.previous_page_number > 1  %}
                                            <li><a href="?page={{i|add:'-2'}}">{{i|add:"-2"}}</a></li>
                                            <li><a href="?page={{i|add:'-1'}}">{{i|add:"-1"}}</a></li>
                                        {% endif %}
                                        <li class="active"><span>{{i}}</span></li>
                                    {% endif %}
                                {% endfor %}
                                
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                                {% else%}
                                    <li><a>&gt;</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock body %}