accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup , name = "signup"),
    path("profile/", views.profile , name = "profile"),
    path("profile/edit/", views.profile_edit , name = "profile_edit"),
    path("profile/password/", views.password_change , name = "password_change"),
]

blog/urls.py
from django.urls import path
from . import views
app_name = "blog"

urlpatterns = [
    path("",views.PostList.as_view(), name= "post_list" ),
    path("<slug:slug>", views.PostDetail.as_view(),name= "post_detail" ),
    path("category/<str:slug>", views.PostByCategory.as_view(),name= "post_by_category" ),
    path("tag/<slug:slug>", views.PostByTag.as_view(),name= "post_by_tag" ),
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from .settings import MEDIA_ROOT

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),    
    path('summernote/', include('django_summernote.urls')),
    path('', include('about.urls', namespace = "about")),
    path("blog/", include("blog.urls", namespace= "blog")),
    path("Property/", include("property.urls", namespace= "property")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings. MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>DirEngine</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    {% block style %}
        
    {% endblock style %}
        
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alex+Brush" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.css'%}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">

    <link rel="stylesheet" href="{% static 'css/aos.css'%}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css'%}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css'%}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="/">dirEngine.</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a href="/" class="nav-link">{% translate "Home"%}</a></li>
                    <li class="nav-item"><a href="/about" class="nav-link">{% translate "About"%}</a></li>
                    <li class="nav-item"><a href="/category/Tour" class="nav-link">{%translate "Tour"%}</a></li>
                    <li class="nav-item"><a href="/Property" class="nav-link">{%translate "Property"%}</a></li>
                    <li class="nav-item"><a href="/blog" class="nav-link">{%translate "Blog"%}</a></li>
                    <li class="nav-item"><a href="/contact" class="nav-link">{%translate "Contact"%}</a></li>
                    <li class="nav-item cta"><a href="/Property/new" class="nav-link"><span>{%translate "Add listing"%}</span></a></li>
                    
                    {% if user.is_authenticated %}
                    <li class="nav-item cta ml-3 dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
                        data-mdb-toggle="dropdown" aria-expanded="false"><iconify-icon icon="charm:person" width="14"></iconify-icon> Profile </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li class="dropdown-item">- {{user.username}} -</li>
                            <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">{%translate  "My account"%}</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout'%}">{%translate "Log out"%}</a></li>
                        </ul>
                    </li>
                    {% else %}

                    <li class="nav-item cta ml-3"><a href="{% url 'login'%}" class="nav-link"><span>{%translate "Login"%}</span></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
    <!-- END nav -->
    {% block body %} 

    {% endblock body %}



    <footer class="ftco-footer ftco-bg-dark ftco-section">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">{{info.name}}</h2>
                        <p>{{info.desc}}</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="{{info.twit_link}}"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="{{info.fb_link}}"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="{{info.insta_link}}"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-5">
                        <h2 class="ftco-heading-2">Information</h2>
                        <ul class="list-unstyled">
                            <li><a href="/about" class="py-2 d-block">About</a></li>
                            <li><a href="#" class="py-2 d-block">Service</a></li>
                            <li><a href="#" class="py-2 d-block">Terms and Conditions</a></li>
                            <li><a href="#" class="py-2 d-block">Become a partner</a></li>
                            <li><a href="#" class="py-2 d-block">Best Price Guarantee</a></li>
                            <li><a href="#" class="py-2 d-block">Privacy and Policy</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Customer Support</h2>
                        <ul class="list-unstyled">
                            <li><a href="/about" class="py-2 d-block">FAQ</a></li>
                            <li><a href="#" class="py-2 d-block">Payment Option</a></li>
                            <li><a href="#" class="py-2 d-block">Booking Tips</a></li>
                            <li><a href="#" class="py-2 d-block">How it works</a></li>
                            <li><a href="/contact" class="py-2 d-block">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have a Questions?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">{{info.address}}</span></li>
                                <li><a href=""><span class="icon icon-phone"></span><span class="text">{{info.call_us}}</span></a></li>
                                <li><a href="mailto:{{info.email}}"><span class="icon icon-envelope"></span><span
                                            class="text">{{info.email}}</span></a></li>
                            </ul>
                        </div>
                        

                        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}">
                            <select name="language">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                        {{ language.name_local }} ({{ language.code }})
                                    </option>
                                {% endfor %}
                            </select>
                            <input type="submit" value="Go">
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>
                            document.write(new Date().getFullYear());
                        </script> All rights reserved | This template is made with <i class="icon-heart"
                            aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>
    
    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00" /></svg></div>


    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.stellar.min.js'%}"></script>
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'js/aos.js'%}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js'%}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js'%}"></script>
    <script src="{% static 'js/scrollax.min.js'%}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false">
    </script>
    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    <script src="{% static 'js/google-map.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>

</body>

</html>